AHoroshii_short_url_redirect:
  controller: AHoroshiiUrlShortenerBundle:UrlShortener:shortUrlRedirect
  path: /{hash}
  method: "GET"

AHoroshii_short_url_create:
  controller: AhorohsiiUrlShortenerBundle:UrlShortener:shortUrlCreate
  path: /short_url_create
