services:
  hashids.hashid_url_shortener:
    class: Hashids\Hashids
    public: true
    arguments:
      - "%url_shortener.hash_salt%"
      - "%url_shortener.hash_min_length%"
      - "%url_shortener.hash_min_alphabet%"
  horoshii_url_shortener.service.url_shortener:
    class: Horoshii\UrlShortenerBundle\Service\UrlShortenerService
    public: true
    arguments:
      - "@hashids.hashid_url_shortener"
      - "@doctrine.orm.entity_manager"
      - "@validator"
      - "%url_shortener.check_user_info%"
